commict discrete collision detection example 1
PhysikaTeam/PhysIKA pull request #11
Opened 2021-04-02 12:15 UTC by Axe-hyx

commit example1

2021-04-22 02:32 UTC, FeiZhu requested changes

2021-04-22 02:32 UTC, FeiZhu commented on Examples/App_Collision/helper.h
> +#include "Dynamics/RigidBody/RigidCollisionBody.h"
1. add include guard for this header
2. make keyfunc() inline to avoid redefinition issue.

2021-04-22 02:32 UTC, FeiZhu commented on Examples/App_Collision/main.cpp
> +#define gap 0.4
replace macro "gap" with a variable

2021-04-22 02:32 UTC, FeiZhu commented on Source/Dynamics/RigidBody/RigidCollisionBody.cpp
> +#include <vector>
include system header before project header

2021-04-22 02:32 UTC, FeiZhu commented on Source/Framework/Topology/TriangleSet.h
> +		std::vector<Triangle> h_triangles;
Difference between h_triangles && m_triangles?

2021-04-22 02:32 UTC, FeiZhu commented on Source/GUI/GlutGUI/GLApp.cpp
> +		glutKeyboardFunc(keyboard_function_);
Could you do me a favor to fix the issue of other setXXXFunction as well?

2021-04-23 23:45 UTC, Axe-hyx commented on Source/Framework/Topology/TriangleSet.h
> +		std::vector<Triangle> h_triangles;
h_triangles store on CPU(host array), m_triangles store on GPU(device array).
h_triangles, h_edges, h_coords are used in copy construction function(data reuse).

2021-05-07 03:04 UTC, merged