Dev
PhysikaTeam/PhysIKA pull request #8
Opened 2021-03-17 06:52 UTC by BenXu86

SWE model
Support megapixel level emulation using MAC grid.

2021-03-22 09:14 UTC, FeiZhu requested changes

2021-03-22 09:14 UTC, FeiZhu commented on Source/Dynamics/HeightField/ShallowWaterEquationModel.cu
> +				}
for loop, if statement, switch statement are highly unfriendly to CUDA. Try to remove if and switch by some tricky manipulation. For instance,
int ix_offset = j < 2 ? 0 : ( j % 2 ? -1 : 1);
int iz_offset = j < 2 ? (j == 1 ? -1 : 1) : 0;
m_velocity[i][2] = 0;
h[i] = h[(ix + ix_offset) * zcount + iz + iz_offset];

2021-03-22 11:21 UTC, BenXu86 commented on Source/IO/Image_IO/image.cpp
> +	for (unsigned int i = 0; i < height; ++i)
We only use this function once to do image preprocessing,  and we won’t use it again.

2021-03-22 11:21 UTC, BenXu86 commented on Source/Rendering/HeightFieldRender.cu
> +			int id = i + j * (heights.Nx() - 1);
yes

2021-03-22 11:32 UTC, BenXu86 commented on Source/Rendering/HeightFieldRender.cu
> +		char str[200];
The synchronization seems unnecessary. But the rendering part is not written by us, so I'm not sure about this. I suggest to keep it like this for now.

2021-03-22 11:37 UTC, BenXu86 commented on Source/Framework/Framework/DeclareEnum.h
> +#include <string>
This file was not changed by us. But the ‘string’ variable in this header file is used by the following class, so it is necessary to include it.

2021-03-22 12:35 UTC, BenXu86 commented on Source/Dynamics/HeightField/ShallowWaterEquationModel.cu
> +				}
Thanks a lot. I learn it. I will make some optimizations for this in particular

2021-03-22 13:17 UTC, BenXu86 commented on Source/IO/Image_IO/image.h
> +    void mergeImage(int h_compressed, int w_compressed);
Now we add the explaination in the function declaration

2021-03-22 13:19 UTC, BenXu86 commented on Source/Dynamics/HeightField/HeightFieldNode.cu
> +		//this->setNumericalModel(swe);
we have deleted the unnecessary comments now.

2021-03-24 09:42 UTC, FeiZhu requested changes

2021-03-24 09:42 UTC, FeiZhu commented on Source/Dynamics/HeightField/HeightFieldNode.cu
> +	std::vector<TDataType::Real>& HeightFieldNode<TDataType>::outputDepth() {
It is danger to return reference of local variable.

2021-03-24 09:42 UTC, FeiZhu commented on Source/IO/Image_IO/image.cpp
> +    raw_data_ = d.data();
d cannot be std::vector considering its memory will be pointed by raw_data_. It must be allocated on heap.

2021-03-25 01:51 UTC, merged